config/routes.rb
Rails.application.routes.draw do
  # get 'pages/home'
  devise_for :users
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new"
  patch "tasks/:id", to:"tasks#update", as: :update_task
  put "tasks/:id", to:"tasks#update_two", as: :update_task_two
  get "tasks/:id", to:"tasks#show", as: :show_task
  delete "tasks/:id", to:"tasks#destroy", as: :destroy_task

  get "/tasks/:id/edit", to: "tasks#edit", as: :edit_task

  get "/admin", to: "pages#admin"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :creator, class_name: "User"
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, foreign_key: "creator_id", dependent: :destroy
end

app/controllers/TurboController.rb
class TurboController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protected 
    def set_task!
        @task = Task.new
        @tasks = Task.all
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_task!
  before_action :authenticate_user! 
  def home

    @tasks = Task.all
  end

  def admin 
  end

  def new 
  end

  private 
  # def set_task

  #   @tasks = Task.all
  # end


  def authenticate_admin!
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user! 
    before_action :set_task!
    def new
        @task = Task.new
    end

    def show
        @task = Task.find(params[:id])
    end

    def destroy
       @task =  Task.find(params[:id])
       if @task.destroy
        redirect_to root_path
       else
        flash.now[:error] = "Task couldn't destroyed"
        render "/pages/home", status: 422
       end
    end
    

    def create 
        puts "AAFDFSFSDFSD"
        @user = current_user
        @task = @user.tasks.create task_params
        if @task.save
            redirect_to root_path, notice: "post created Successfully "
        else
            render "pages/home" , status: 422
        end
    end

    def update
        @task = Task.find(params[:id])
        


        if @task.update_attribute(:completed, !@task.completed)
          redirect_to root_path
        else
          flash[:error] = "Something went wrong"
          puts "EERRRRROOORR"
          redirect_to root_path, status: 422
        end
    end

    def edit
        @task = Task.find(params[:id])
    end
    

    def update_two
        @task = Task.find(params[:id])
        
        print task_params
        print "AADSFAFSDFSDFSDF"
        print task_params

        if @task.update(task_params)
          flash[:success] = "Object was successfully updated"
          redirect_to show_task_path(@task)
        else
          flash[:error] = "Something went wrong"
          puts "EERRRRROOORR"
          render :edit , status: 422
        end
    end
    
    
    def new
        @task = Task.new
        
    end
    
    
    private
    # def set_task
    #     @task = Task.new
    #     @tasks = Task.all
    #   end
    

    def task_params
        params.require(:task).permit(:content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

     <%=render "shared/navbar"%>
     <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
     <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/admin.html.erb
<h1>Admin Page</h1>

app/views/pages/home.html.erb
    
<div class="d-flex justify-center w-100">
<div class="wrapper">
<table id="customers">

  <thead>
    <tr>
      <th>Pending Task</th>
      <th>Created At</th>
      <th>Completed</th>
      <th></th>
    </tr>
  </thead>
  <% if current_user %>
     <%current_user.tasks.each do |task|%> 
    <%= render 'shared/task', task:task %>
   <% end %>  
    
  <% end %>
  
 
  
</table>


 </div>




</div>
 

app/views/shared/_form.html.erb
<%= form_with model: task  do |f| %>

    <%if task.errors.any?%>
    <%task.errors.full_messages.each do |msg|%>
        <div> <%=msg%></div>
    <% end %>
    <% end %>
  <div style="margin-bottom:1rem">
    <%= f.label :content %>
    <br>
    
    <%= f.text_field :content %>
  </div>
  <div >
    <%= f.submit "Add Todo", class:'btn' %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class = "navbar">  
     <div class="brand-collapse">
      <%=link_to "Todos", root_path, class:"navbar-brand"%>
      <%=link_to "+ Add", tasks_new_path, class:"add-todo-btn"%>
     </div>
   
    <ul>

    <% if current_user %>
            <li><%=link_to root_path do%>
            <%=current_user.email.split("@")[0]%>

        <% end %> 
        
        </li>
      
    <% end %>


        

        
        
            <%if current_user %>
            <li>
                <%=button_to destroy_user_session_path, method: :delete do%><p class="nav-link">Logout</p><% end %>

            </li>
            <% else %>
                <li>
                <%=link_to new_user_session_path do%><p class="nav-link">Login</p><% end %>
                </li>
                <li>
                <%=link_to new_user_registration_path do%><p class="nav-link">Sign Up</p><% end %>
                </li>
                
            <% end %>
             

       
        
        </li>
    </ul>


</nav>

app/views/shared/_task.html.erb
 
      <tr>
         <td style="font-weight:700;" ><%=link_to  show_task_path(task) do%> 
         <%=task.content%> <% end %>  
         </td>
         <td style="color: #a5aab0;"><%=task.created_at.to_s.split(" ").first%> </td>
         <td><%=button_to update_task_path(task) , method: :patch , style:"margin-left:1.8rem" do%>
                <% if !task.completed %>
                     <div class="check-box" id="check-box">
                    ✓
                     </div>
                     <% else %>
                      <div class="check-box check-box-active" id="check-box">
                    ✓
                </div>
                  
                <% end %>
               
             <% end %>
         </td>
         <td><%=button_to  destroy_task_path(task), class:"delete-btn" , method: :delete do%>
         <i class="ri-delete-bin-line bin"></i>
         <% end %>
         
         </td>
      </tr>
    

  

app/views/tasks/edit.html.erb
<h1>update_task_two</h1>



<section class="task-new-section">

    <div class="task-input d-flex justify-center">
        <%= form_with model: @task , url:update_task_two_path(@task) ,method: :put do |f| %>

    <%if @task.errors.any?%>
    <%@task.errors.full_messages.each do |msg|%>
        <div> <%=msg%></div>
    <% end %>
    <% end %>
  <div style="margin-bottom:1rem">
    <%= f.label :content %>
    <br>
    
    <%= f.text_field :content %>
  </div>
  <div >
    <%= f.submit "Update Todo", class:'btn'%>
  </div>
<% end %>
    </div>
</section>

app/views/tasks/new.html.erb
<section class="task-new-section">

    <div class="task-input d-flex justify-center">
        <%= render 'shared/form' ,task: @task %>
    </div>
</section>

app/views/tasks/show.html.erb
<div class="show-task d-flex justify-center mt-4">

    <div class="task-wrapper" >
        <div class="d-flex justify-between align-center">
            <h2 class="task-h2"><%=@task.content%> </h2>
            <div class="show-icons d-flex justify-between"> 

            <%=button_to  destroy_task_path(@task) , method: :delete , class:"delete-btn-edit", form_class: "myButton" do%>
                 <i class="ri-delete-bin-line bin"></i>
            <% end %>

            <%=link_to edit_task_path do %><i class="ri-edit-line edit"></i>  <% end %>   
            </div>
        </div>

        <h4 class="task-h4">Created By: <%=@task.creator.email.split("@").first%> </h4>
        
    
    
    </div>

</div>